# NXCTL configuration

challenges:
  # github_repo: https://github.com/nxctf/nxctl-challenges
  github_repo: https://github.com/ariafatah0711/ctfc_chall
  branch: main
  access_token: ${GITHUB_TOKEN}

app:
  data_dir: ./data
  # base_ip: "192.168.56.101"

api:
  token: ${NXCTL_API_TOKEN}
  admin_secret: ${NXCTL_API_ADMIN_SECRET}

ttl:
  default_minutes: 15
  extend_minutes: 10
  extend_threshold_minutes: 5
  extend_cooldown_seconds: 30

daemon:
  interval_seconds: 10
  restart_cooldown_seconds: 300

exports:
  auto_heal: true
  endpoint_check_interval_seconds: 120
  endpoint_check_timeout_seconds: 20

ports:
  local_start: 40000
  local_end: 49999
  randomize: true

tunnels:
  default: localtunnel
  ngrok:
    enabled: true
    max_sessions_per_token: 3
    tokens:
      - ${NGROK_TOKEN_1}
      - ${NGROK_TOKEN_2}
      - ${NGROK_TOKEN_3}
      - ${NGROK_TOKEN_4}
      - ${NGROK_TOKEN_5}
      - ${NGROK_TOKEN_6}
      - ${NGROK_TOKEN_7}
      - ${NGROK_TOKEN_8}
      - ${NGROK_TOKEN_9}
      - ${NGROK_TOKEN_10}
  localtunnel:
    enabled: true
  cloudflare:
    enabled: false
  pinggy:
    enabled: true
    max_sessions_per_token: 1
    # tokens:
    #   - ${PINGGY_TOKEN_1}
    #   - ${PINGGY_TOKEN_2}
