# CTF Challenge Orchestration Engine Configuration

github_repo: https://github.com/ariafatah0711/b
branch: main
access_token: ${GITHUB_TOKEN}

cache_dir: ./data/chall
build_dir: ./data/build
db_file: ./data/ctf-orch.db

default_tunnel: localtunnel
enable_ngrok: true
enable_localtunnel: true
enable_pinggy: true

# TTL settings
default_ttl_minutes: 2
extend_time_minutes: 1
extend_threshold_minutes: 1

ngrok_tokens:
  - ${NGROK_TOKEN_1}
  - ${NGROK_TOKEN_2}
  - ${NGROK_TOKEN_3}
  - ${NGROK_TOKEN_4}
  - ${NGROK_TOKEN_5}
  - ${NGROK_TOKEN_6}

pinggy_token: ${PINGGY_TOKEN}
