"""Constants for NXCTL."""

# Service types
SERVICE_TYPE_HTTP = "http"
SERVICE_TYPE_TCP = "tcp"
SERVICE_TYPES = [SERVICE_TYPE_HTTP, SERVICE_TYPE_TCP]

# Runtime status
RUNTIME_STATUS_STOPPED = "stopped"
RUNTIME_STATUS_RUNNING = "running"
RUNTIME_STATUS_ERROR = "error"
RUNTIME_STATUSES = [RUNTIME_STATUS_STOPPED, RUNTIME_STATUS_RUNNING, RUNTIME_STATUS_ERROR]

# Export providers
EXPORT_PROVIDER_NGROK = "ngrok"
EXPORT_PROVIDER_LOCALTUNNEL = "localtunnel"
EXPORT_PROVIDER_PINGGY = "pinggy"
EXPORT_PROVIDER_CLOUDFLARE = "cloudflare"
EXPORT_PROVIDER_BASE_IP = "base_ip"
EXPORT_PROVIDERS = [
    EXPORT_PROVIDER_NGROK,
    EXPORT_PROVIDER_LOCALTUNNEL,
    EXPORT_PROVIDER_PINGGY,
    EXPORT_PROVIDER_CLOUDFLARE,
]

# Export status
EXPORT_STATUS_ACTIVE = "active"
EXPORT_STATUS_INACTIVE = "inactive"

# Protocol types
PROTOCOL_HTTP = "http"
PROTOCOL_TCP = "tcp"

# Port defaults
DEFAULT_SERVICE_PORT = 8080
DEFAULT_NGROK_STARTUP_TIMEOUT = 12  # seconds
DEFAULT_LOCALTUNNEL_STARTUP_TIMEOUT = 10  # seconds
DEFAULT_PINGGY_STARTUP_TIMEOUT = 10  # seconds
DEFAULT_CLOUDFLARE_STARTUP_TIMEOUT = 15  # seconds

# Provider protocols
# ngrok: http only
# localtunnel: http only
# pinggy: tcp only
# cloudflare: http only
PROVIDER_PROTOCOLS = {
    EXPORT_PROVIDER_NGROK: [PROTOCOL_HTTP],
    EXPORT_PROVIDER_LOCALTUNNEL: [PROTOCOL_HTTP],
    EXPORT_PROVIDER_PINGGY: [PROTOCOL_TCP],
    EXPORT_PROVIDER_CLOUDFLARE: [PROTOCOL_HTTP],
}
